### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by lena-hinrichsen** [SinaB0ck/OCR4all#16]
Hi, I noticed a few misdirecting links:

- the "Edit this page" links in the footer do not work, e.g. it's https://github.com/OCR4all/OCR4all.github.io//edit/main/about.md (does not work) instead of 
https://github.com/OCR4all/OCR4all.github.io/edit/main/docs/about.md (works)
=> remove one slash and add `docs/` when generating the link

- In `ocr4all-setup_guide_virtualbox_ger.pdf` and `ocr4all-setup_guide_virtualbox_eng.pdf ` the link `https://ocr4all.org/vm-download_de.php` should be updated to `https://www.ocr4all.org/software_download/vm-download.html`

**Comment by maxnth** [comment]
Hi, excuse the (very) late reply.
Thanks for the suggestions!

>the "Edit this page" links in the footer do not work

The "Edit this page" button was completely removed by us so it shouldn't be an issue anymore :sweat_smile: 

>In ocr4all-setup_guide_virtualbox_ger.pdf and ocr4all-setup_guide_virtualbox_eng.pdf the link https://ocr4all.org/vm-download_de.php should be updated to https://www.ocr4all.org/software_download/vm-download.html

Yeah, the PDF guides are sadly horribly outdated. Parts of the team are currently in the process of moving all the guides to this website so hopefully we don't need the PDF files anymore.
